# Project description

**Importing the libraries**

In [ ]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



**Loading the data**

In [ ]:
df_data= pd.read_csv("/content/spambase_csv.csv")
df_data.head(3)


word_freq_make  word_freq_address  ...  capital_run_length_total  class
0            0.00               0.64  ...                       278      1
1            0.21               0.28  ...                      1028      1
2            0.06               0.00  ...                      2259      1

[3 rows x 58 columns]

In [24]:
df_data.shape

(4601, 58)

# Cleaning the data

In [26]:
# Checking the datatypes
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 

In [25]:
# Checking for missing values
df_data.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_fre

We do not have missing data and all the columns are numerical data types

# Feature reduction

We will use PCA to reduce our features

In [28]:
# Getting the features
X = df_data.drop('class', 1)
y = df_data['class']

In [29]:
# Splitting the data into train and test data
# We will use 80-20 ratio to split our dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [30]:
# Standardising the data set
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
# Applying PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

# Model one

**Naive Bayes**

In [32]:
# Importing Naive bayes libraries
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB


In [33]:
# Training the model
clf = GaussianNB()  
model = clf.fit(X_train, y_train) 

In [34]:
# # Predicting our test predictors
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8447339847991314


In [38]:
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score
print(confusion_matrix(y_test, predicted))

print("Accuracy score GNB:",metrics.accuracy_score(y_test, predicted)*100)
print("Precision score GNB:",metrics.precision_score(y_test, predicted)*100)
print("Recall score GNB:",metrics.recall_score(y_test, predicted)*100)
f1 = f1_score(y_test, predicted)
print('F1 score: %f' % f1)

[[443  95]
 [ 48 335]]
Accuracy score GNB: 84.47339847991314
Precision score GNB: 77.90697674418605
Recall score GNB: 87.46736292428199
F1 score: 0.824108


**Model one results**

Our accuracy is 84%, precision score is 78%, Recall score is 87% and F1 Score is 82%

# Model two

**Using a split of 70-30**

In [39]:
# Getting the features
X = df_data.drop('class', 1)
y = df_data['class']

In [40]:
# Splitting the data into train and test data
# We will use 70-30 ratio to split our dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [42]:
# Using PCA to reduce the features
# Standardising the data set
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Applying PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

**Applying the model**

In [55]:
# Training the model
clf2 = GaussianNB()  
model2 = clf2.fit(X_train, y_train) 

In [56]:
# Predicting our test predictors
predicted2 = model2.predict(X_test)
print(np.mean(predicted2 == y_test))

0.8712656165127648


In [57]:
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score
print(confusion_matrix(y_test, predicted2))

print("Accuracy score GNB:",metrics.accuracy_score(y_test, predicted2)*100)
print("Precision score GNB:",metrics.precision_score(y_test, predicted2)*100)
print("Recall score GNB:",metrics.recall_score(y_test, predicted2)*100)
f1 = f1_score(y_test, predicted2)
print('F1 score: %f' % f1)

[[964 133]
 [104 640]]
Accuracy score GNB: 87.12656165127648
Precision score GNB: 82.79430789133248
Recall score GNB: 86.02150537634408
F1 score: 0.843771


**Model two results**

Our accuracy is 87%, precision score is 82%, Recall score is 86% and F1 Score is 84%

# Model three

**Using a split of 60-40**

In [46]:
# Getting the features
X = df_data.drop('class', 1)
y = df_data['class']

In [47]:
# Splitting the data into train and test data
# We will use 60-40 ratio to split our dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [48]:
# Using PCA to reduce the features
# Standardising the data set
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Applying PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

**Applying the model**

In [53]:
# Training the model
clf3 = GaussianNB()  
model3 = clf3.fit(X_train, y_train) 

In [54]:
# Predicting our test predictors
predicted3 = model3.predict(X_test)


In [58]:
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score
print(confusion_matrix(y_test, predicted3))

print("Accuracy score GNB:",metrics.accuracy_score(y_test, predicted3)*100)
print("Precision score GNB:",metrics.precision_score(y_test, predicted3)*100)
print("Recall score GNB:",metrics.recall_score(y_test, predicted3)*100)
f1 = f1_score(y_test, predicted3)
print('F1 score: %f' % f1)

[[964 133]
 [104 640]]
Accuracy score GNB: 87.12656165127648
Precision score GNB: 82.79430789133248
Recall score GNB: 86.02150537634408
F1 score: 0.843771


**Model three results**

Our accuracy is 87%, precision score is 82%, Recall score is 86% and F1 Score is 84%

# Conclusion

> Using a split lower than 80-20 gives the model better prediction. However; extreme splits i.e 40-60 could lead to underfitting

